name: ChatABC

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read issue content
        id: read-issue
        run: echo "content=${{ github.event.issue.body }}" >> $GITHUB_OUTPUT

      - name: Send POST request
        id: send-request
        run: |
          response=$(curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$${{ steps.read-issue.outputs.content }}\"}" https://gpt4free.awdev.repl.co/quick)
          echo "response=$response" >> $GITHUB_OUTPUT

      - name: Extract server response
        id: extract-response
        run: |
          echo '${{ steps.send-request.outputs.response }}' > result.json
          result=$(jq '.response' 'result.json')
          echo "result is $result"
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Close & Reply Issue
        id: close-and-reply
        run: |
          gh issue close https://github.com/AWeirdScratcher/most-sane-repo/issues/${{ github.event.issue.number }} --comment "${{ steps.extract-response.outputs.result }}" --reason "cheese"
