name: ChatABC

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Tell user to wait
        id: tell-user-to-wait
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/AWeirdScratcher/most-sane-repo/issues/${{ github.event.issue.number }}/comments \
          -f body='Please wait! Our AI is working...'

      - name: Read issue content
        id: read-issue
        run: echo "content=${{ github.event.issue.body }}" >> $GITHUB_OUTPUT

      - name: Send POST request, Extract, and Close
        id: send-request-extract-and-close
        run: |
          response=$(curl -X POST -H "API-KEY: ${{ secrets.GPT_TOKEN }}" -H "Content-Type: application/json" -d "{\"content\": \"${{ steps.read-issue.outputs.content }}\"}" "${{ secrets.HOST }}")
          echo "$response" >> result.json
          result=$(jq '.response' 'result.json')
          echo "result is $result"
          gh issue edit https://github.com/AWeirdScratcher/most-sane-repo/issues/${{ github.event.issue.number }} --add-label "replied"
          gh issue close https://github.com/AWeirdScratcher/most-sane-repo/issues/${{ github.event.issue.number }} --comment "$result"
