name: ChatABC

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read issue content
        id: read-issue
        run: echo "content=${{ github.event.issue.body }}" >> $GITHUB_OUTPUT

      - name: Send POST request, Extract, and Close
        id: send-request-extract-and-close
        run: |
          response=$(curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$${{ steps.read-issue.outputs.content }}\"}" https://gpt4free.awdev.repl.co/quick)
          echo "$response" >> result.json
          result=$(jq '.response' 'result.json')
          echo "result is $result"
          gh issue edit https://github.com/is-probably-gay/is-probably-gay/issues/${{ github.event.issue.number }} --add-label "replied"
          gh issue close https://github.com/AWeirdScratcher/most-sane-repo/issues/${{ github.event.issue.number }} --comment "$result"
